# version: '3'
services:
  backend:
    image: my-backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: my-frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: always
# version: '3'
# services:
#   backend:
#     build: ./backend
#     ports:
#       - '5001:5000'
#     volumes:
#       - ./backend:/app
#     environment:
#       - NODE_ENV=development

#   frontend:
#     build: ./frontend
#     ports:
#       - '3000:80'
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     depends_on:
#       - backend
