services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: my-backend
    ports:
      - '5001:5000'
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: always
