services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: my-backend
    ports:
      - '5001:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/api/health']
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-frontend
    ports:
      - '80:80'
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:5000
    restart: always
