
[[languages]]
language = "nodejs"
path = "backend"
command = "npm install --prefix backend && npm run build --prefix backend && npm run start --prefix backend"

[[languages]]
language = "nodejs"
path = "frontend"
command = "npm install --prefix frontend && npm run build --prefix frontend"
