[[languages]]
language = "nodejs"
path = "backend"
install = "npm install"
build = "npm run build"
start = "npm run start"

[[languages]]
language = "nodejs"
path = "frontend"
install = "npm install -g serve && npm install"
build = "npm run build"
start = "vite preview --host --port 80"
